### ISSUE TITLE
Iceland Death Total goes from 5 to 1

### ISSUE THREAD

**Issue by brentthorne** [CSSEGISandData/COVID-19#1009]
From this file:

[time_series_19-covid-Deaths.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv) 

I have found that Iceland reports 5 deaths on March 15th 2020 then the following day death total goes to 0. On March 17th and 18th the total goes to 1 death. 

I am not sure what the correct numbers are but I thought you may want to know, there are more like this for the USA and I will post a separate issue for that when I can identify all of them.

Great work so far to all involved, this is not a simple job!

**Comment by irshadk** [comment]
I have published a detailed error report for all the categories and dates here in #1013

**Comment by biggikalli** [comment]
In the case of Iceland, must have been a mistype into deaths instead of recovered. Iceland has 5 recovered atm.
The 1 death was unconfirmed, the individual was young, died suddenly, had atypical symptoms but tested positive. So the report was corrected until later, when it was confirmed that his death was caused by pneumonia from the Covid infection.

**Comment by brucify** [comment]
This error still exists with the new csv file. Deaths toll jumps back from 5 to 0 on 3/15/20 then jumps back from 0 to 1 on 3/20/20:
[time_series_covid19_deaths_global.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv)
```
Iceland | ...... | 0 | 0 | 5 | 0 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | 2 | 2 | 2 | ...
```
