### ISSUE TITLE
Virginia (and us) death totals wrong

### ISSUE THREAD

**Issue by samkrva** [CSSEGISandData/COVID-19#1795]
IN the daily data upload for 3/29 the death data for Virginia is 21. In the 3/30 upload its 15. Impossible. The VA Dept of health says 25. The county of Henrico VA is really 8 and data upload says 2. 

Let me know if there is some other place I can get the death by county for VA. 

The totals for the US don't agree with the JH interactive map either.

**Comment by CSSEGISandData** [comment]
There are 10 deaths in VA without assigned locations from the official website (https://www.virginia.gov/coronavirus/). We won't be able to show them on the map with a dot. We will figure out a way to display it in the dashboard and match up with the official counts. Thanks!

**Comment by samkrva** [comment]
I have audited the data in VA based on reports from the DEPARTMENT of health press releases. I have created a CSV with the fixes to the proper counties. How do I upload?

**Comment by samkrva** [comment]
I'll be glad to do this every day?

**Comment by samkrva** [comment]
Thanks
I've fixed the data for va based on the press releases from the department of health
Bill

William J. Kenney
Kenney Ventures, LLC
Kenney Consulting
804.353.1440
bill.k@kenneyventures.com

This communication constitutes an electronic communication within the Electronic Communications Privacy Act,19 USC 2510, and it's disclosure is strictly limited to the recipient. If you are not the intended recipient please contact the sender. No Kinsale company is liable if an attachment is altered without its written written consent.



On Mar 31, 2020, at 1:28 AM, CSSEGISandData <notifications@github.com> wrote:

﻿

There are 10 deaths in VA without assigned locations from the official website (https://www.virginia.gov/coronavirus/<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.virginia.gov_coronavirus_&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=WRkbElxjv2oYymTV7lXfkhxVvR9PL20RwTpME33tYFc&m=FiqC8gz3rvLgHDIlr7IUpytJCCVbpodj7Blt1VmbYkc&s=i-i__inmHXhXUSmdDTojuX4IyGaTVCFZskH6Yu068Bg&e=>). We won't be able to show them on the map with a dot. We will figure out a way to display it in the dashboard and match up with the official counts. Thanks!

**Comment by CapinWinky** [comment]
Various dashboards and whatnot that pull from here like https://91-divoc.com/pages/covid-visualization/ still show Virginians coming back to life on March 30th.

**Comment by oltdaniel** [comment]
@samkrva The data here is not only the official reported numbers, it is also collected from other sources. This will result in manual work (delays) and different numbers. Like the corona.rki.de reports every day with official numbers not every state does that and so numbers need to be estimated with different sources, So please respect the work done here and all changes one to the format or data.

**Comment by weslawson** [comment]
Virginia has now started reporting the Deaths in Virginia by County - http://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv

**Comment by weslawson** [comment]
As of today, Virginia has posted historical cases, deaths and hospitalization data with the newest data.   

> UPDATE: 4/23/20 - In addition to today's counts, this data set now includes historical data of cumulative counts by date.   VDH COVID-19-PublicUseDataset-Cases
