### ISSUE TITLE
Florida Data 4/13/2020

### ISSUE THREAD

**Issue by czdz** [CSSEGISandData/COVID-19#2167]
You're showing over 100,000 cases in Florida on 4/13/2020.  This does not seem correct.

**Comment by MuletownBrown** [comment]
Check Okaloosa County ... 102,103?

**Comment by vk4tdi** [comment]
Looks to me like there is a comma missing for Okaloosa County (FIPS=12091). Line ends:
...69,78,80,83,91,101,102103

**Comment by Ricks-Lab** [comment]
Is this also impacting the global confirmed file?

**Comment by jkbishay** [comment]
Report shows Okaloosa should in fact be 103 cases, not 102,103:
https://www.thedestinlog.com/news/20200413/coronavirus-by-countycity-statewide-deaths-at-499-okaloosa-santa-rosa-report-more-cases-other-nwf-counties-remain-unchanged

This is likely the due to the error @vk4tdi pointed out and it appears to be affecting just about all files for April 13th.

**Comment by aakash-sahai** [comment]
I can tell that you are getting this erroneous data from 1point3acres, where I first noticed the issue. They have fixed the error since. You just need to refresh the data.

**Comment by PeterDowdy** [comment]
Also reported in https://github.com/CSSEGISandData/COVID-19/issues/2166

**Comment by tylerhg** [comment]
There has not been any new commits so I don't know how the issue could be fixed.  The data is still showing 682,619 total cases in the US.

**Comment by advaithasabnis** [comment]
They'll notice and fix soon since their dashboard is also showing the wrong number so I guess just wait for it.

**Comment by GerardoRTobar** [comment]
@tylerhg It hasn't been fixed yet. Actually, their online dashboard shows that error too... 

I hope they fix it soon

**Comment by aakash-sahai** [comment]
Guys, there dashboard was fixed at least 15 minutes ago. Please refresh.

**Comment by aakash-sahai** [comment]
![Screen Shot 2020-04-13 at 6 32 00 PM](https://user-images.githubusercontent.com/5730614/79173537-1f8b5900-7db5-11ea-8d4d-dbeece5d9981.png)

**Comment by GerardoRTobar** [comment]
mmm nope, it still shows 682,619... I just refreshed. How many cases does it show to you @aakash-sahai?

**Comment by aakash-sahai** [comment]
Hmm, that is strange. I posted the screenshot with a 6:13 PM MDT timestamp. It is 6:33 PM MDT now. Some web-cache has it wrong, if others see a different picture.

**Comment by vk4tdi** [comment]
1point3acres gets US data from https://covidtracking.com/, which references Florida's dashboard. Florida's official number is 103 for Okaloosa. 
![Florida](https://user-images.githubusercontent.com/27050652/79173628-7fc4de00-7e3b-11ea-8e3f-f198dea40b33.png)

**Comment by czdz** [comment]
You guys are discussing two different dashboards.  1point3acres has been fixed.  Johns Hopkins dashboard has not been fixed.

**Comment by aakash-sahai** [comment]
Cool. Things are improving. Top level US numbers look good on JHU dashboard, but FL numbers are still inflated.

**Comment by ei-JoanneT** [comment]
> They'll notice and fix soon since their dashboard is also showing the wrong number so I guess just wait for it.

Do they usually fix wrong data points at night? Have to deliver something tomorrow morning so I am not sure if I should manually fix it on my end or wait

**Comment by GerardoRTobar** [comment]
The fixed it already, but the daily report. They haven't updated the time series, which is the one we use the most, I think.

**Comment by aakash-sahai** [comment]
Whole world looks at JHU dashboard. Very few look at 1point3acres. It does not bode well for you guys. Have you contacted them to fix the time-series data?

**Comment by duh931** [comment]
https://github.com/CSSEGISandData/COVID-19/pull/2170
Opened this for hit fix. Not sure how soon they will respond though.

**Comment by aaroncolesmith** [comment]
Just pulled a corrected version

**Comment by ei-JoanneT** [comment]
In the daily report, the Okaloosa confirmed case for 04.13 is fixed, yet the active case is still showing 102102

**Comment by BJReplay** [comment]
> Just pulled a corrected version

Will this be included in the global time series or do you need a fix for that submitted as well?

**Comment by aaroncolesmith** [comment]
time_series_covid19_confirmed_global.csv looks to be fixed; time_series_covid19_confirmed_US.csv looks to still have incorrect data

**Comment by aaroncolesmith** [comment]
Now both time_series_covid19_confirmed_global & time_series_covid19_confirmed_US look fine

**Comment by aakash-sahai** [comment]
All else looks good but the total confirmed cases for world is still inflated, and the graph too.

**Comment by MBtech** [comment]
The daily reports file still had the wrong number of active cases. Made the pull request #2171 to fix that
