### ISSUE TITLE
Time series data updated with empty column?

### ISSUE THREAD

**Issue by picklejason** [CSSEGISandData/COVID-19#300]
![image](https://user-images.githubusercontent.com/57494592/76154267-765f8d80-60a7-11ea-82c2-140da999774d.png)
Don't know if this is an error or if it takes time to update (haven't noticed it before) but the empty column is messing with my project since it reads in the last column.

**Comment by lazd** [comment]
Duplicate of #299

**Comment by picklejason** [comment]
Issue has been resolved, the data in the column is in

**Comment by jtene001** [comment]
Problem is not resolved. There are still 5 incomplete rows.
Tempe, AZ #39 
Santa Clara, CA #65 
Providence, RI #123 
Berkeley, CA #145 
Norwell County, MA #195 

Last cell is missing for all five.

**Comment by Bost** [comment]
> Issue has been resolved, the data in the column is in

Yea, except that erroneous data stays in the caches of API services.

This bad-commit thing repeats every day so it's kind hard of hard to stay polite... :(

https://github.com/CSSEGISandData/COVID-19/issues/238
