### ISSUE TITLE
Dashboard NO DATA

### ISSUE THREAD

**Issue by betancour** [CSSEGISandData/COVID-19#337]
Recently the dashboard display as **NO DATA**

![image](https://user-images.githubusercontent.com/283403/76221738-483d9300-61f8-11ea-82d7-cf74cbbdc9c3.png)

**Comment by ciscorucinski** [comment]
The stock market crash probably sent a huge number of users to the dashboard and crashed it

**Comment by davidkogxg** [comment]
No red dots on my machine.

**Comment by JeremiahGillis** [comment]
No data and no red dots on my map.

![image](https://user-images.githubusercontent.com/13179985/76229506-f2f98580-61e7-11ea-9f59-7adea4d03eda.png)

**Comment by CSSEGISandData** [comment]
Due to the influx of traffic we are experiencing technical issues. Our team is working to resolve the issue. Sorry for the inconvenience. There is no estimated time of recovery at the moment.

**Comment by smz** [comment]
I might be wrong, but it seems to me that there is some issue with Italian data (and maybe German too...) and that is causing issues on the global data too...

**Comment by betancour** [comment]
they must open this dashboard to be sponsored by aws and google or azure due to the high rate traffic.

**Comment by smz** [comment]
it looks fine right now from here (Italy)...

**Comment by JeremiahGillis** [comment]
Seems to be working again in the USA.

**Comment by betancour** [comment]
> it looks fine right now from here (Italy)...

Yes, seems like it's fixed. 

TY all, specially devs involved

**Comment by smz** [comment]
> TY all, specially devs involved

+1!

**Comment by benjackman** [comment]
Looks fixed, great effort all

**Comment by carterjeff** [comment]
Fixed! thanks devs!

**Comment by CSSEGISandData** [comment]
The issue has been resolved. Thank you for your patience.

**Comment by ciscorucinski** [comment]
Issues still persist. As you can see, I still get the `Not fully configured` messages all over the place

![Screenshot from 2020-03-10 10-10-51](https://user-images.githubusercontent.com/8707125/76270193-abdac580-62b7-11ea-94a2-8778769c0e73.png)
![Screenshot from 2020-03-10 10-11-02](https://user-images.githubusercontent.com/8707125/76270198-b1381000-62b7-11ea-94fc-f33e4c96d0e5.png)
