### ISSUE TITLE
Compilation of French data ?

### ISSUE THREAD

**Issue by JLB-Lyon** [CSSEGISandData/COVID-19#4002]
Hello, 
Congratulations for your wonderful work on the compilation and treatment of coronavirus data !
Would you know why the the graphical representations of French  data (daily cases, daily deaths, ...)  are not available anymore (since early April) ?
I apologize to you if it was not the right way to contact you.
Thanks for your time.
Regards,
 
J.luc

**Comment by CSSEGISandData** [comment]
Hello,

Thank you for your message. We will look into this error and hope to have it resolved shortly.

**Comment by CSSEGISandData** [comment]
Thank you again. The issue is resolved.

**Comment by JLB-Lyon** [comment]
Thanks for your quick answer, but the issue persists ?
A red circle now appears on France in the world map, but the graphical representation of the data (daily cases, daily deaths, ...), on the bottom right side of the screen, doesn't seem to work. I just get the mention "aucune donnée" (no data) .

It's working with other countries.

Regards,
