### ISSUE TITLE
Daily deaths and cases in France

### ISSUE THREAD

**Issue by HannahRitchie** [CSSEGISandData/COVID-19#4939]
Hello JHU,

Is there possibly an error in France's daily case and death count for 22nd November? 

Both appear to show a huge, anomalous increase in the last day (which doesn't appear to be in line with the Government's data (https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/):
https://bit.ly/3FF9lWm
https://bit.ly/3HPpwC7

Thank you!

**Comment by odadoun** [comment]
Hello Hannah,

you definitely right.
In red the data from OWID in blue the Data from Sante Public France (the deaths here are the cumul between the deaths in hospital and in nursing home)
![image](https://user-images.githubusercontent.com/11535234/143044509-7993e0a4-eb0b-46f4-9e4f-c2bb4ee8d2f9.png)
cheers
olivier

**Comment by CSSEGISandData** [comment]
Hi Hannah,

Thanks so much for notifying us of this (I actually saw your post on Twitter first) and apologies that it took some time to solve. We fixed the data yesterday. 
The issue arose due to a slight bug in our algorithm for removing the cases/deaths in France territories from the total for the mainland. It has since been patched so hopefully this does not occur again.

**Comment by edomt** [comment]
Hi @CSSEGISandData 

It seems like there's still an issue with cases unfortunately:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/7103774/143261909-0174cb02-5242-463e-93ad-e2277acff992.png">
