### ISSUE TITLE
Germany: Number Of Confirmed Cases: drop in cumulative values 

### ISSUE THREAD

**Issue by DataOps-epam** [CSSEGISandData/COVID-19#5632]
Dear JHU,
Could you please check your time series "Germany: Number Of Confirmed Cases" here: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

We can see drop in cumulative values for 04/01/2022 period since its initial release.
Could you please advise on this.

Thank you.

#DEU.CONFIRMED.COVID19.D@JHU

**Comment by CSSEGISandData** [comment]
Hello,

We found an error in our pipeline leading to an inflation of Germany cases in the "Unaassigned, Germany" category from April 1, 2022 on. This was corrected directly to master.

**Comment by DataOps-epam** [comment]
Hi, we still see that 01.04 value is less than 31.03 in the source file - https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Could you please clarify. Thank you.
