### ISSUE TITLE
Incorrect Ontario, Canada data

### ISSUE THREAD

**Issue by michaelbooth1** [CSSEGISandData/COVID-19#5892]
Covid deaths for Ontario, Canada are incorrect. Currently it is showing a massive spike that appears to be an incorrect interpretation of the Government backfilling some additional column data. As you can see the difference between the current deaths on Google for Ontario, Canada and those reported by reputable journalists such as here

https://twitter.com/jm_mcgrath/status/1547644202632196098?t=a47T0aImnQpH_MmPGa3jfg&s=19

**Comment by lucasrodes** [comment]
Issue also reported in https://github.com/owid/covid-19-data/discussions/2698

**Comment by CSSEGISandData** [comment]
Thank you for the notification. We are investigating.

**Comment by Dmole** [comment]
I like how from 2022-03-15 to 2022-03-21 the data shows COVID resurrected 38 people.

**Comment by danwalker9999** [comment]
The official Ontario government COVID dashboard does not show 1,153 COVID deaths on July 14.
It shows 3 deaths.
https://www.publichealthontario.ca/en/Data-and-Analysis/Infectious-Disease/COVID-19-Data-Surveillance/COVID-19-Data-Tool?tab=trends

JHU really needs to fix this, now.

**Comment by CSSEGISandData** [comment]
Addressed in #5933. The spike in deaths was genuine and due to the Ontario government pausing death data reporting for several months. This data has now been overwritten using the new methodology published by the source which does not contain a similar spike due to the changed definition of COVID-19 death.

**Comment by Dmole** [comment]
@CSSEGISandData Is there any similar way to address the 38 undead people?

**Comment by CSSEGISandData** [comment]
@Dmole thank you for your comment. As noted in #5933 and referenced above, the historical data has been overwritten. You'll find that your concern is addressed by that change.

**Comment by Dmole** [comment]
@CSSEGISandData I's still seeing the issue at the 37k mark as shown in this image:

![Screenshot_20220727-083530_Fennec](https://user-images.githubusercontent.com/1793802/181248481-55dbd5a0-bd61-46a3-8f4a-b759836355ac.png)
